Add rule S4144 No identical functions
SonarSource/sonar-go-archived pull request #16
Opened 2018-02-28 18:14 UTC by saberduck

fix #15

2018-02-28 18:22 UTC, saberduck commented
Test is currently failing because I can't implemented exceptions the same way as they are done in Java. We should discuss how to handle this.

2018-03-01 10:28 UTC, ghost requested changes
@saberduck make the example compliant then. If we don't manage the same exceptions, let's at least accept them for the time being (so change the test file). I however thing that we could make the rule stricter and also covers the parameters.

2018-03-01 10:28 UTC, m-g-sonar commented on common-rule-engine/src/main/java/org/sonar/uast/helpers/FunctionLike.java
> +  public static FunctionLike from(UastNode node) {
I would add a `@CheckForNull` annotation there.

2018-03-01 10:28 UTC, m-g-sonar commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/NoIdenticalFunctionsCheck.java
> +        if (syntacticallyEquivalent(thisFunction.body(), function.body())) {
What if there is different arguments? Or empty bodies?

2018-03-01 10:28 UTC, m-g-sonar commented on common-rule-engine/src/main/java/org/sonar/uast/helpers/FunctionLike.java
> +  public static final UastNode.Kind KIND = UastNode.Kind.FUNCTION;
I would prefer `FUNCTION_KIND`

2018-03-01 13:51 UTC, saberduck commented on common-rule-engine/src/main/java/org/sonar/uast/helpers/FunctionLike.java
> +  public static final UastNode.Kind KIND = UastNode.Kind.FUNCTION;
I disagree, this constant should be used as `FunctionLike.KIND` , so having `FUNCTION` again in the name would be redundant

2018-03-01 13:52 UTC, saberduck commented on common-rule-engine/src/main/java/org/sonar/uast/helpers/FunctionLike.java
> +  public static FunctionLike from(UastNode node) {
There should be a rule for this ;-)

2018-03-01 15:46 UTC, saberduck commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/NoIdenticalFunctionsCheck.java
> +        if (syntacticallyEquivalent(thisFunction.body(), function.body())) {
added comparison for parameters and exclude methods with less than 2 statements

2018-03-01 15:46 UTC, saberduck commented
@m-g-sonar please have a look at my changes

2018-03-01 16:44 UTC, ghost approved these changes

2018-03-01 16:44 UTC, merged