Fix #83 RSPEC-1479 switch with too many cases
SonarSource/sonar-go-archived pull request #219
Opened 2018-04-10 13:20 UTC by benzonico

2018-04-10 16:48 UTC, alban-auzeill requested changes

2018-04-10 16:48 UTC, alban-auzeill commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/SwitchWithTooManyCaseCheck.java
> +      reportIssue(switchLike.switchKeyword(), String.format("Reduce the number of non-empty switch cases from %d to at most %d.", casesNb, maximumCases));
The "empty switch case" exception is not in this implementation and it's fine. Remove "non-empty" from the message.

2018-04-10 16:48 UTC, alban-auzeill commented on common-rule-engine/src/test/files/checks/SwitchWithTooManyCaseCheck/SwitchWithTooManyCaseCheck.java
> +//	^^^^^^
Our test framework does not support tab characters. To align issue location, replace tab by spaces

2018-04-10 16:48 UTC, alban-auzeill commented on common-rule-engine/src/test/files/checks/SwitchWithTooManyCaseCheck/SwitchWithTooManyCaseCheck.go
> +type f struct {
This struct seems useless for this test. remove it and the 'x' parameter of the foo function in the 2 go test files.

2018-04-11 08:13 UTC, benzonico commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/SwitchWithTooManyCaseCheck.java
> +      reportIssue(switchLike.switchKeyword(), String.format("Reduce the number of non-empty switch cases from %d to at most %d.", casesNb, maximumCases));
interestingly, the emptyness of cases is not tested in SonarJava... Message updated.

2018-04-11 08:55 UTC, benzonico commented
@alban-auzeill Review comments applied and fixed.

2018-04-11 09:10 UTC, alban-auzeill approved these changes

2018-04-11 09:11 UTC, merged