Report On Comments
SonarSource/sonar-go-archived pull request #247
Opened 2018-04-17 11:18 UTC by stylianos-agapiou-sonarsource

2018-04-17 11:36 UTC, saberduck commented on common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/TestUtils.java
> +      if (from == null && to == null) {
It will be better to test that `from` is a `COMMENT` with `primary.from.is(UastNode.Kind.COMMENT)` and call `onRange` with token information as you did. Do not use `onLine`

2018-04-18 07:45 UTC, vilchik-elena requested changes

2018-04-18 07:45 UTC, vilchik-elena commented on common-rule-engine/src/test/java/org/sonar/commonruleengine/checks/TestUtils.java
> +      UastNode fromUastNode = primary.from;
@stylianos-agapiou-sonarsource name can be simplified `fromNode`, `toNode`

2018-04-18 08:39 UTC, vilchik-elena approved these changes

2018-04-18 08:40 UTC, merged