Rule S1066: Collapsible 'if' statements should be merged
SonarSource/sonar-go-archived pull request #275
Opened 2018-04-24 13:47 UTC by vilchik-elena

fixes #87

2018-04-24 15:46 UTC, saberduck requested changes
I think that we need to exclude pattern when nested if is initializing a variable

2018-04-24 15:46 UTC, saberduck commented on its/ruling/src/test/expected/go-S1066.json
> +'project:kubernetes/cmd/kubelet/app/bootstrap.go':[
I think we should exclude cases where there is variable initialization in the nested if, because this can't be always merged

2018-04-26 08:55 UTC, vilchik-elena commented on its/ruling/src/test/expected/go-S1066.json
> +'project:kubernetes/cmd/kubelet/app/bootstrap.go':[
@saberduck I will do that for Go, but it's a nice example of exclusion specific to language to keep in mind when implementing UAST 2.0

2018-04-26 09:49 UTC, saberduck approved these changes

2018-04-26 09:53 UTC, merged