Fix #88 function should not have too many lines
SonarSource/sonar-go-archived pull request #276
Opened 2018-04-24 14:32 UTC by benzonico

2018-04-24 14:54 UTC, vilchik-elena requested changes

2018-04-24 14:54 UTC, vilchik-elena commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/FunctionTooBigCheck.java
> +      reportIssue(from.name(), String.format("This function has %s lines of code, which is greater than the %s authorized. Split it into smaller functions.", size, max));
@benzonico do you plan to fix this issue of NPE?

2018-04-24 14:54 UTC, vilchik-elena commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/FunctionTooBigCheck.java
> +    super(UastNode.Kind.FUNCTION);
@benzonico what about function literal? IMO it should be supported by this rule

2018-04-24 14:54 UTC, vilchik-elena commented on common-rule-engine/src/test/files/checks/FunctionTooBigCheck/FunctionTooBigCheck.go
> +package FunctionName
@benzonico `FunctionName`?

2018-04-24 14:54 UTC, vilchik-elena commented on common-rule-engine/src/test/files/checks/FunctionTooBigCheck/FunctionTooBigCheck.go
> +type AI interface {
@benzonico why this declaration? it seems to not be used (same for other file)

2018-04-24 14:54 UTC, vilchik-elena commented on common-rule-engine/src/test/files/checks/FunctionTooBigCheck/FunctionTooBigCheckMax5.go
> +func foo2() { // Noncompliant {{This function has 6 lines of code, which is greater than the 5 authorized. Split it into smaller functions.}}
@benzonico can we test something in the middle? smaller than max but > 0

2018-04-24 15:34 UTC, benzonico commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/FunctionTooBigCheck.java
> +      reportIssue(from.name(), String.format("This function has %s lines of code, which is greater than the %s authorized. Split it into smaller functions.", size, max));
I struggle to see the point : I can add a null check but then how do I actually test it ?

2018-04-24 15:39 UTC, benzonico commented on common-rule-engine/src/test/files/checks/FunctionTooBigCheck/FunctionTooBigCheck.go
> +type AI interface {
I was expecting the method declared to be mapped with kind FUNCTION (and so the functionLike would produce null) but it is not the case, this construction has no uast kind.

2018-04-24 15:40 UTC, benzonico commented on common-rule-engine/src/test/files/checks/FunctionTooBigCheck/FunctionTooBigCheck.go
> +type AI interface {
I think keeping this construction in the test file is a nice safety net for eventual future mapping or uast construction.

2018-04-24 15:44 UTC, vilchik-elena commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/FunctionTooBigCheck.java
> +      reportIssue(from.name(), String.format("This function has %s lines of code, which is greater than the %s authorized. Split it into smaller functions.", size, max));
@benzonico don't test it, or at least wont-fix the issue at next

2018-04-24 15:45 UTC, benzonico commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/FunctionTooBigCheck.java
> +    super(UastNode.Kind.FUNCTION);
https://jira.sonarsource.com/browse/RSPEC-1188 for me this is another rule.

2018-04-24 17:19 UTC, saberduck commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/FunctionTooBigCheck.java
> +    super(UastNode.Kind.FUNCTION);
fyi: https://discuss.sonarsource.com/t/rspec-1188-could-be-common-rule/381

2018-04-26 06:46 UTC, benzonico commented
@vilchik-elena can you do another round of review on that one ?

2018-04-26 08:22 UTC, merged