Rule S1172: Unused function parameters should be removed
SonarSource/sonar-go-archived pull request #288
Opened 2018-04-27 13:40 UTC by vilchik-elena

fixes #80

2018-04-27 14:59 UTC, saberduck requested changes
I think computation can be made more effective

2018-04-27 14:59 UTC, saberduck commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/UnusedParameterCheck.java
> +      } else {
Maybe we can avoid `else` clause because control flow is terminated in `if`

2018-04-27 14:59 UTC, saberduck commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/UnusedParameterCheck.java
> +      if (!isParameterUsed(node, parameterName)) {
we can compute all used identifiers in the body only once and then do set intersection, it should be much more effective

2018-04-30 06:38 UTC, vilchik-elena commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/UnusedParameterCheck.java
> +      } else {
@saberduck we should have a rule for that!

2018-04-30 06:39 UTC, vilchik-elena commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/UnusedParameterCheck.java
> +      } else {
@saberduck but it's inside loop

2018-04-30 09:34 UTC, saberduck requested changes

2018-04-30 09:34 UTC, saberduck commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/UnusedParameterCheck.java
> +      return identifiersInBody.stream().anyMatch(identifier -> identifier.token != null && identifier.token.value.equals(name));
this is still iterating through the whole set instead of just using `contains`. You should have a set of strings

2018-04-30 09:34 UTC, saberduck commented on common-rule-engine/src/main/java/org/sonar/commonruleengine/checks/UnusedParameterCheck.java
> +    if (parameterName.is(Kind.IDENTIFIER) && parameterName.token != null) {
you can probably move this tests to the part where you are collecting parameters

2018-04-30 12:06 UTC, saberduck approved these changes

2018-04-30 12:06 UTC, merged