Create "go vet" report sensor
SonarSource/sonar-go-archived pull request #313
Opened 2018-05-29 14:07 UTC by alban-auzeill

2018-05-30 12:27 UTC, vilchik-elena requested changes

2018-05-30 12:27 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoPlugin.java
> +        .description("Paths (absolute or relative) to the files with \"go vet\" errors/issues.")
@alban-auzeill IMO you should use either `errors` or `issues`, not both)

2018-05-30 12:27 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/AbstractReportSensor.java
> +public abstract class AbstractReportSensor implements Sensor {
@alban-auzeill  how about putting it in commons?))

2018-05-30 12:27 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/GoVetReportSensor.java
> +      }
@alban-auzeill `else` log warning in debug?

2018-05-30 12:27 UTC, vilchik-elena commented on its/plugin/projects/samples/go-vet.sh
> +go vet 2> go-vet.out || [ $? == 1 ]
@alban-auzeill why we need this file committed? IMO it's better create README in this dir explaining how to generate report

2018-05-30 12:27 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/it/go/GoVetReportTest.java
> +          issue.line() + "|" +
@alban-auzeill tiny improvement can be done: add 'line' before/after line, otherwise it takes time to understand what is this number about

2018-05-30 12:27 UTC, vilchik-elena commented on its/plugin/projects/samples/go-vet.sh
> +go vet 2> go-vet.out || [ $? == 1 ]
@alban-auzeill is it possible to configure rule set?

2018-05-30 12:27 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/AbstractReportSensor.java
> +        .type(RuleType.CODE_SMELL)
@alban-auzeill I have a feeling now that all go-vet rules are bugs, wdyt?

2018-05-30 12:27 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/externalreport/GoVetReportSensorTest.java
> +    assertThat(sensorDescriptor.name()).isEqualTo("Import of govet issues");
@alban-auzeill `Go Vet`? or `go-vet`? or `"go vet"`?:)

2018-05-30 12:40 UTC, alban-auzeill commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoPlugin.java
> +        .description("Paths (absolute or relative) to the files with \"go vet\" errors/issues.")
It's a copy and paste from your code https://github.com/SonarSource/SonarTS/blame/master/sonarts-sq-plugin/sonar-typescript-plugin/src/main/java/org/sonar/plugin/typescript/TypeScriptPlugin.java#L121
I'm going to only keep "issues".

2018-05-30 12:42 UTC, alban-auzeill commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/AbstractReportSensor.java
> +public abstract class AbstractReportSensor implements Sensor {
Do you mean moving this abstract class in a new sub-package named "commons"?

2018-05-30 12:44 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/AbstractReportSensor.java
> +public abstract class AbstractReportSensor implements Sensor {
No, I mean here https://github.com/SonarSource/sonar-analyzer-commons

2018-05-30 12:44 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoPlugin.java
> +        .description("Paths (absolute or relative) to the files with \"go vet\" errors/issues.")
ha-ha:) sorry

2018-05-30 12:52 UTC, alban-auzeill commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/GoVetReportSensor.java
> +      }
Ok, I will log none empty lines that we can't parse using debug level.

2018-05-30 12:57 UTC, alban-auzeill commented on its/plugin/projects/samples/go-vet.sh
> +go vet 2> go-vet.out || [ $? == 1 ]
Ok I will move the command in a README file, even if it's not possible to execute a README.
About the rule set, by default it's all rules, otherwise we can provide a list of argument to activate rule one by one. For now, I will keep all rules even is some are duplicated with our rules.

2018-05-30 13:14 UTC, alban-auzeill commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/AbstractReportSensor.java
> +        .type(RuleType.CODE_SMELL)
Yes, I agree. "go vet" issues are  more bug than code smell.
GoMetaLinter has two level of severity: warning and error.
And it always assume that "go vet" produce error (https://github.com/alecthomas/gometalinter/blob/2ecd20cca240c07a9277a0849f34e8822213edff/config.go#L117)

2018-05-30 13:16 UTC, alban-auzeill commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/externalreport/GoVetReportSensorTest.java
> +    assertThat(sensorDescriptor.name()).isEqualTo("Import of govet issues");
There's no name. The project is "Vet". You invoke it using "go vet". The doc is at "go doc cmd/vet"...
So I'm going to replace by "go vet"

2018-05-30 13:18 UTC, alban-auzeill commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/AbstractReportSensor.java
> +public abstract class AbstractReportSensor implements Sensor {
Let's speak about this during the third copy and paste implementation.

2018-05-31 08:41 UTC, vilchik-elena approved these changes

2018-05-31 08:42 UTC, merged