Match rule key from govet message
SonarSource/sonar-go-archived pull request #316
Opened 2018-06-01 16:05 UTC by andrea-guarino-sonarsource

2018-06-04 08:07 UTC, vilchik-elena requested changes

2018-06-04 08:07 UTC, vilchik-elena commented on its/plugin/tests/src/test/java/com/sonar/it/go/ExternalLinterReportTest.java
> -        "SelfAssignement.go|external_golint:issue|MAJOR|5min|line:1|package comment should be of the form \"Package samples ...\"\n" +
@andrea-guarino-sonarsource why order of issues is different?

2018-06-04 08:07 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/AbstractReportSensor.java
> +              report.getPath(), e);
@andrea-guarino-sonarsource I'm not sure about this change of formatting

2018-06-04 08:07 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/AbstractReportSensor.java
> +              .forRule(RuleKey.of(issue.linter, mapRuleKey(issue.ruleKey, issue.message, issue.linter)))
@andrea-guarino-sonarsource how about extracting rule key computation? otherwise it's 3 levels of call nesting

2018-06-04 08:07 UTC, vilchik-elena commented on sonar-go-plugin/src/test/README.md
> +To generate file `all-govet-report`:
@andrea-guarino-sonarsource should be golint?

2018-06-04 08:07 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/AbstractReportSensor.java
> +
@andrea-guarino-sonarsource should not be empty line

2018-06-04 08:07 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/AbstractReportSensor.java
> +  private static String mapRuleKey(@Nullable String ruleKey, String message, String linter) {
@andrea-guarino-sonarsource we can pass just `ExternalIssue` as parameter

2018-06-04 08:07 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/GoLintReportSensor.java
> +      return new ExternalIssue(LINTER_ID, RuleType.CODE_SMELL, null, filename, lineNumber, message);
@andrea-guarino-sonarsource how about looking for key when creating issue?

2018-06-04 08:07 UTC, vilchik-elena commented on sonar-go-plugin/src/test/README.md
> +go tool vet <PATH TO GO REPO>/src/cmd/vet/testdata 2>&1 | sed 's/[^:]*:[0-9]*:/main.go:1:/ > ./resources/externalreport/all-govet-report.txt'
@andrea-guarino-sonarsource where is file `main.go`?

2018-06-04 08:07 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/externalreport/GoLintReportSensorTest.java
> +  void should_match_golint_all_keys() throws IOException {
@andrea-guarino-sonarsource can we discuss the point of this test?

2018-06-04 08:07 UTC, vilchik-elena commented on sonar-go-plugin/src/test/resources/externalreport/all-govet-report.txt
> +main.go:1: direct assignment to atomic value
@andrea-guarino-sonarsource why same message many times?

2018-06-04 08:18 UTC, alban-auzeill commented on its/plugin/tests/src/test/java/com/sonar/it/go/ExternalLinterReportTest.java
> -        "SelfAssignement.go|external_golint:issue|MAJOR|5min|line:1|package comment should be of the form \"Package samples ...\"\n" +
Because method "formatIssues" sort the result alphabetically.

2018-06-04 08:30 UTC, alban-auzeill commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/externalreport/GoLintReportSensor.java
> +      return new ExternalIssue(LINTER_ID, RuleType.CODE_SMELL, null, filename, lineNumber, message);
In the current implementation, an issue imported from a golint report or a golint issue imported from a GoMetaLinter report, the message is converted to a rule key at the same code source location.

2018-06-04 08:51 UTC, andrea-guarino-sonarsource commented on sonar-go-plugin/src/test/README.md
> +go tool vet <PATH TO GO REPO>/src/cmd/vet/testdata 2>&1 | sed 's/[^:]*:[0-9]*:/main.go:1:/ > ./resources/externalreport/all-govet-report.txt'
It's created inside `createContext` method used for tests.
[https://github.com/SonarSource/sonar-go/blob/bad3ddc69501faa8fc0e9a11013236b728a305b3/sonar-go-plugin/src/test/java/org/sonar/go/plugin/externalreport/ExternalLinterSensorHelper.java#L48](https://github.com/SonarSource/sonar-go/blob/bad3ddc69501faa8fc0e9a11013236b728a305b3/sonar-go-plugin/src/test/java/org/sonar/go/plugin/externalreport/ExternalLinterSensorHelper.java#L48)

2018-06-04 08:57 UTC, andrea-guarino-sonarsource commented on sonar-go-plugin/src/test/resources/externalreport/all-govet-report.txt
> +main.go:1: direct assignment to atomic value
When running `golint` on testdata, messages came from different files/locations.
Since we change the file name to `main.go`, there are some duplicates.
Btw I agree, we should remove duplicate lines.

2018-06-04 11:50 UTC, vilchik-elena commented
add unit test for golint and/or govet when no matching key found

2018-06-04 11:50 UTC, vilchik-elena requested changes

2018-06-04 11:50 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/externalreport/GoLintReportSensorTest.java
> +    for (ExternalIssue externalIssue : externalIssues) {
@andrea-guarino-sonarsource simplify with `ExternalKeyUtils.lookUp..`

2018-06-04 11:50 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/externalreport/GoVetReportSensorTest.java
> +  void all_issues_with_sonarqube_72() throws IOException {
@andrea-guarino-sonarsource drop sonarqube from name

2018-06-04 11:50 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/externalreport/GoVetReportSensorTest.java
> +  void all_issues_with_sonarqube_72() throws IOException {
@andrea-guarino-sonarsource test that none externalIssues have `issue` key (same for Golint)

2018-06-04 11:50 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/externalreport/GoVetReportSensorTest.java
> +  void should_match_govet_keys() throws IOException {
@andrea-guarino-sonarsource move assertions from here to `issues_with_sonarqube_72`

2018-06-04 11:52 UTC, vilchik-elena commented on sonar-go-plugin/src/test/README.md
> +go tool vet <PATH TO GO REPO>/src/cmd/vet/testdata 2>&1 | sed 's/[^:]*:[0-9]*:/main.go:1:/ > ./resources/externalreport/all-govet-report.txt'
@andrea-guarino-sonarsource explain how this file is generated and why we need it

2018-06-05 08:01 UTC, vilchik-elena approved these changes

2018-06-05 08:13 UTC, merged