Support GOPATH with multiple entries when importing the coverage (Fix #308)
SonarSource/sonar-go-archived pull request #322
Opened 2018-06-06 14:00 UTC by alban-auzeill

Extract GOPATH path resolution mechanism so test report sensor could use it

2018-06-06 15:55 UTC, vilchik-elena requested changes

2018-06-06 15:55 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/GoPathContextTest.java
> +  void source_directories() {
`multiple_source_directories_in_gopath`

2018-06-06 15:55 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/GoPathContextTest.java
> +  void resolve_using_go_path() throws IOException {
split this test in several

2018-06-06 15:55 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/GoPathContextTest.java
> +  void resolve_using_go_path() throws IOException {
add test with 2 valid path in gopath

2018-06-06 15:55 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/GoPathContextTest.java
> +    assertThat(linuxContext.resolveUsingGoPath("my-app/my-app.go")).isEqualTo("/home/paul/go/src/my-app/my-app.go");
line can be removed

2018-06-06 15:55 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/GoPathContextTest.java
> +    assertThat(windowsContext.resolveUsingGoPath("my-app\\my-app.go")).isEqualTo("C:\\Users\\paul\\go\\src\\my-app\\my-app.go");
same

2018-06-06 15:55 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoPathContext.java
> +  String resolveUsingGoPath(String filePath) {
how about just `resolve`?

2018-06-06 15:55 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoPathContext.java
> +  private String prefixByFirstGoPath(String filePath) {
can you add comment explaining this hack

2018-06-06 15:55 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/GoPathContextTest.java
> +  void concat() {
split test

2018-06-06 15:55 UTC, vilchik-elena commented on sonar-go-plugin/src/test/java/org/sonar/go/plugin/GoPathContextTest.java
> +    GoPathContext linuxContext = new GoPathContext('/', ":", "/home/paul/go:/home/luc/go");
how about having path separator at the end? `"/home/paul/go:/home/luc/go:"`

2018-06-06 16:05 UTC, alban-auzeill commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoPathContext.java
> +  private String prefixByFirstGoPath(String filePath) {
added on the resolve(...) method

2018-06-06 17:07 UTC, alban-auzeill commented
@vilchik-elena please review my last commit

2018-06-07 08:13 UTC, vilchik-elena approved these changes

2018-06-07 08:13 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoPathContext.java
> +   * Try to resolve the absolute path of the given filePath. If filePath is relative,
@alban-auzeill You forgot to mention about normalization of already absolute path

2018-06-07 08:13 UTC, vilchik-elena commented on sonar-go-plugin/src/main/java/org/sonar/go/plugin/GoPathContext.java
> +   * See GoCoverageReport#findInputFile to understand why a non-existing file is useful.
@alban-auzeill this "See" is mean:) there is no doc for `GoCoverageReport#findInputFile`. You could also use `{@link..}`

2018-06-07 09:41 UTC, merged